name: heart_disease_mobile_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  dio: ^5.6.0
  equatable: ^2.0.5

  # flutter_gen: any
dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/heart_logo.png
  color_dark: "#ffffff" # Specify white for dark mode as well
  image_dark: assets/images/heart_logo.png

  android_12:
    image: assets/images/heart_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/heart_logo.png
    icon_background_color_dark: "#ffffff"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/front_heart.jpg
